application:
  subdomain: lychee
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://lychee:80/
services:
  lychee:
    # docker.io/linuxserver/lychee:6.4.2
    # upstream: docker.io/linuxserver/lychee:7.8.2
    image: docker.1ms.run/linuxserver/lychee:7.8.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DB_CONNECTION=mysql
      - DB_HOST=lychee-db
      - DB_PORT=3306
      - DB_USERNAME=lychee
      - DB_PASSWORD={{ stable_secret "database_password" }}
      - DB_DATABASE=lychee
      - APP_NAME=Lychee
      - APP_ENV=production
      - APP_URL=${LAZYCAT_APP_DOMAIN}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - TRUSTED_PROXIES=*
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/pictures:/pictures
    depends_on:
      - lychee-db
  lychee-db:
    # docker.io/library/mariadb:10.11
    # upstream: docker.io/library/mariadb:10.11.19
    image: docker.1ms.run/library/mariadb:10.11.19
    environment:
      - MYSQL_ROOT_PASSWORD={{ stable_secret "database_root_password" }}
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD={{ stable_secret "database_password" }}
    binds:
      - /lzcapp/var/db:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - healthcheck.sh --connect --innodb_initialized
      start_period: 60s
