lzc-sdk-version: "0.1"
name: Lychee
package: cloud.lazycat.app.lychee
version: 6.4.2
description: 图片管理工具
homepage: https://lycheeorg.dev
author: lychee
application:
  subdomain: lychee
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://lychee:80/
services:
  lychee:
    image: docker.hlmirror.com/linuxserver/lychee:6.4.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DB_CONNECTION=mysql
      - DB_HOST=lychee-db
      - DB_PORT=3306
      - DB_USERNAME=lychee
      - DB_PASSWORD=lychee
      - DB_DATABASE=lychee
      - APP_NAME=Lychee
      - APP_ENV=production
      - APP_URL=${LAZYCAT_APP_DOMAIN}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - TRUSTED_PROXIES=*
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/pictures:/pictures
    depends_on:
      - lychee-db

  lychee-db:
    container_name: lychee-db
    image:  docker.hlmirror.com/mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=lychee
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lychee
    binds:
      - /lzcapp/var/db:/var/lib/mysql
    health_check:
      test:
        - CMD-SHELL
        - healthcheck.sh --connect --innodb_initialized
      start_period: 60s